

let all_news = [
    {
      id: 1,
     title: "Nigeria Football News",
      category: "Football",
      image: "https://cdn.pixabay.com/photo/2023/09/21/06/10/football-8266065_640.jpg",
     description: "Stay updated with the latest developments in Nigerian football. From player performances to match results, get all the key insights. This is your go-to source for everything football in Nigeria.",
      Date: "30-11-2024",
    },
    {
      id: 2,
     title: "African Football News",
      category: "Football",
      image: "https://cdn.pixabay.com/photo/2024/06/26/01/16/ai-generated-8853844_640.jpg " ,
      description: "Covering all the action across Africa's football leagues and tournaments. Get exclusive news, match highlights, and player updates from the continent. Stay in the loop with Africa’s vibrant football scene",
      Date: "30-11-2024",
    },
    {
      id: 3,
     title: "World Football News",
      category: "Football",
      image: "https://cdn.pixabay.com/photo/2016/06/15/01/11/soccer-1457988_640.jpg",
      description: "A global view of football events and updates from around the world. Stay informed on major international leagues and tournaments. Get breaking news, match previews, and post-match analyses",
      Date: 100.5,
    },
    {
      id: 4,
     title: "Match Tracker",
      category: "Football",
      image: "https://cdn.pixabay.com/photo/2017/12/16/17/39/fun-3023031_640.jpg",
      description: "Track football matches in real time with live updates and scores. Perfect for those who want to stay on top of every goal and game-changing moment. Follow all the action from your favorite teams and leagues",
      Date: "30-11-2024",
    },
    {
      id: 5,
     title: "Live Football Scores",
      category: "Football",
      image: "https://cdn.pixabay.com/photo/2023/03/06/17/05/football-7833929_640.jpg",
      description: "Follow live football scores from matches across the world. Get real-time updates on goals, assists, and key events. Ideal for keeping up with matches as they unfold.",
      Date: "30-11-2024",
    },
    {
      id: 6,
     title: "Football League",
      category: "Football",
      image: "https://cdn.pixabay.com/photo/2015/07/02/00/08/football-828218_640.jpg",
      description: "Explore the latest standings, stats, and results from top football leagues. Stay updated with match schedules, team performances, and league rankings. Perfect for passionate football fans.",
      Date: "30-11-2024",
    },
    {
      id: 7,
     title: "Indoor Football",
      category: "Football",
      image: "https://cdn.pixabay.com/photo/2018/04/11/21/19/soccer-3311817_640.jpg",
      description: "Indoor football is a fast-paced and exciting game. Get the latest on leagues, teams, and match results. Stay connected to this thrilling sport with all the updates you need.",
      Date: "30-11-2024",
    },
    {
      id: 8,
     title: "Goal Analysis",
      category: "Football",
      image: "https://cdn.pixabay.com/photo/2023/11/16/09/01/ai-generated-8391922_640.jpg",
      description: "Dive deep into goal statistics and analysis from football matches. Learn about player performance, tactical strategies, and key moments. Get detailed insights on how goals were scored and their impact on matches.",
      Date: "30-11-2024",
    },
    {
      id: 9,
     title: "Comic Football",
      category: "Football",
      image: "https://cdn.pixabay.com/photo/2023/04/13/17/54/ai-generated-7923130_640.jpg",
      description: "Enjoy a lighter, humorous take on the world of football with comics and jokes. Get your daily dose of football fun through cartoons and stories. Perfect for football fans who love to laugh.",
      Date: "30-11-2024",
    },
    {
      id: 10,
     title: "National League Info",
      category: "Football",
      image: "https://media.istockphoto.com/id/484868394/photo/soccer-players-in-action.jpg?s=1024x1024&w=is&k=20&c=ucs87glF6dZeUELA8xSuFcGiyGvLaOYmxLgtmwWMD0g=",
      description: "Find all the essential information about national football leagues. Track team standings, scores, and results from domestic leagues. Stay informed about the top teams and their performance.",
      Date: "30-11-2024",
    },
    {
      id: 11,
     title: "Football Tournaments Info",
      category: "Football",
      image: "https://media.istockphoto.com/id/481074558/photo/soccer-players-in-action-panorama.jpg?s=612x612&w=0&k=20&c=BS6_bQ5T1fUAD2WLLRA6MLcVBTnl0sesYNb3B7wG92I=",
      description: "Get detailed information on major football tournaments worldwide. From the World Cup to regional competitions, stay updated on fixtures, results, and key players. Ideal for tournament fans.",
      Date: "30-11-2024",
    },
    {
      id: 12,
     title: "Beach Football",
      category: "Football",
      image: "https://media.istockphoto.com/id/1186099671/photo/soccer-player-in-action.jpg?s=612x612&w=0&k=20&c=axgQIIj9nydsxslngJvfSel33JDkwSpUDkPOWzvZ6tc= ",
      description: "Explore the fast-growing sport of beach football. Follow updates on tournaments, player stats, and match highlights. Dive into the exciting world of football played on the sand.",
      Date:"30-11-2024",
    },
    {
      id: 13,
     title: "Football Touchdown Stats",
      category: "American Football",
      image: "https://cdn.pixabay.com/photo/2012/11/28/11/11/football-67701_640.jpg",
      description: "Get all the stats and data for American football touchdowns. Track key plays, player achievements, and game-winning touchdowns. Stay informed on the stats that define the sport.",
      Date: "30-11-2024",
    },
    {
      id: 14,
     title: "Pro Football Players",
      category: "American Football",
      image: "https://media.istockphoto.com/id/1367719700/photo/green-field-in-american-football-stadium-ready-for-game-in-the-midfield.jpg?s=612x612&w=0&k=20&c=Cwu6hwmtP6l2MeNxSJ8ynTenQBQ2GsUwVaODfsjpn00=",
      description: "Learn about the best professional football players. Explore player profiles, career highlights, and stats. Stay updated on player transfers and their impact on the game.",
      Date: "30-11-2024",
    },
    {
      id: 15,
     title: "US Football Game",
      category: "American Football",
      image: " https://media.istockphoto.com/id/496853834/photo/sunny-american-football-stadium.jpg?s=612x612&w=0&k=20&c=KdItfhXJs3iMWVIR2yuYdgmjXaMHdqgZCpPFQaojyD4=",
      description: "Follow all the action from US football games. Get game summaries, scores, and player highlights. Stay on top of the latest happenings in American football.",
      Date: "Nov-30-2024",
    },
    {
      id: 16,
     title: "American Football Insights",
      category: "American Football",
      image: "https://media.istockphoto.com/id/929498422/photo/slam-dunk-on-a-basketball-court.jpg?s=612x612&w=0&k=20&c=LaP7s3xJ9cnIK0uKWfs9oVies2RZRTeyZrXPX38L7Gc=",
      description:"Gain in-depth insights into the world of American football. From tactical breakdowns to player performances, stay informed with expert analysis. Perfect for true football fans.",
      Date: "30-11-2024",
    },
    {
      id: 17,
     title: "Fantasy Grid Iron Stats",
      category: "American Football",
      image: " https://media.istockphoto.com/id/144324835/photo/breaking-the-tackle.jpg?s=612x612&w=0&k=20&c=WYRVlLC1xsnZPHM0UmfCJwTp7G1cNQKLuvUr-BWzdrQ=",
      description: "Track fantasy football stats for the gridiron. Stay on top of player performances and fantasy rankings. Get all the data you need to build the perfect fantasy team.",
      Date: "30-11-2024",
    },
    {
      id: 18,
     title: "Live NFL Game Updates",
      category: "American Football",
      image: "https://media.istockphoto.com/id/654140124/photo/american-football-fans-among-falling-confetti.jpg?s=612x612&w=0&k=20&c=dwvkGWNftjGbUY1w90hCkIWnFd_pyPMpEiCNKc68vHw=",
      description: "Follow live updates from the NFL, with real-time scores and game analysis. Get highlights of key plays and moments as they happen. Perfect for NFL enthusiasts who need live action.",
      Date: "30-11-2024",
    },
    {
      id: 19,
     title: "US Football League Stats",
      category: "American Football",
      image: " https://media.istockphoto.com/id/521437599/photo/american-football.jpg?s=612x612&w=0&k=20&c=rpwLwIXX-VjVFlMQpTkv7G9FgF9jtq7RJfXLKnxOHuw=",
      description: "Keep track of all the key statistics in the US football league. From team rankings to player stats, stay informed with the latest data. Get detailed performance reports for every match.",
      Date: "30-11-2024",
    },
    {
      id: 20,
     title: "Football TouchDown Tracker",
      category: "American Football",
      image: "https://media.istockphoto.com/id/488875303/photo/football.jpg?s=612x612&w=0&k=20&c=ofAvdz4HKjEElUcgAEgFYguWU4GRSs7fH7QmXfCBVm8=",
      description: "Track every touchdown in American football with live updates and stats. Stay on top of all the scoring plays and game-changing moments. Perfect for fans who love a good touchdown highlight",
      Date: "30-11-2024",
    },
    {
      id: 21,
     title: "American Football Events",
      category: "American Football",
      image: "https://media.istockphoto.com/id/1382270684/photo/dynamic-portrait-of-male-american-football-player-in-sports-equipment-at-stadium-in-motion-on.jpg?s=612x612&w=0&k=20&c=L3UhtVlWyQ1P4JSoo-OVfbaPnXiXKqRcdXvb4ZL2j2M=",
      description: "Stay updated on the biggest American football events. From local games to major tournaments, follow the action with event schedules, team info, and news. Get exclusive insights into top football happenings.",
      Date: "30-11-2024",
    },
    {
      id: 22,
     title: "College Football",
      category: "American Football",
      image: "https://media.istockphoto.com/id/529662610/photo/football-player-runs-with-the-ball.jpg?s=612x612&w=0&k=20&c=FcqmXy9OX0EBCQdYIJA0GAkb0V2SAC853gL5WB-hliM= ",
      description:"Follow college football action with news, scores, and player profiles. Keep up with the top teams, matchups, and college football rankings. Ideal for those who love the collegiate gridiron scene",
      Date: "30-11-2024",
    },
    {
      id: 23,
     title: "American Football Grid Iron Game Stats",
      category: "American Football",
      image: "https://media.istockphoto.com/id/671176544/photo/boys-high-school-basketball-team.jpg?s=612x612&w=0&k=20&c=iEjr_5I0K5hr6S_bQ6sZnT3zoBWYhTadTTvH09CRo1c=",
      description: "Dive into American football gridiron stats with detailed game analyses. Track touchdowns, yardage, and player performances. Stay informed with up-to-date stats and performance insights.",
      Date: "30-11-2024",
    },
    {
      id: 24,
     title: "American Football NFL Team Roster Data",
      category: "American Football",
      image: "https://media.istockphoto.com/id/1128732235/photo/cheerful-black-family-cheering-while-watching-rugby-match-on-tv-at-home.jpg?s=612x612&w=0&k=20&c=kI2v7qLnbpFoKtKYbN3kHV9FU61B9HEwflV6Hb8ahhU=",
      description:"Explore the latest NFL team rosters with detailed player data. Stay updated on team line-ups, key player stats, and performance trends. Perfect for NFL fans and analysts.",
      Date: "30-11-2024",
    },
    {
      id: 25,
     title: "BasketBall Game Result",
      category: "Basket",
      image: "https://media.istockphoto.com/id/484541018/photo/basketball-arena.jpg?s=612x612&w=0&k=20&c=xckG-hsbTF_lNZ-PhRpKoPvhN9yvP_jLFGFx7tSPq-E=",
      description: "Get the latest results from basketball games across the globe. Stay updated with scores, key moments, and team performances. Perfect for basketball fans who want fast access to game results.",
      Date: "30-11-2024",
    },
    {
      id: 26,
     title: "NBA Player Profiles",
      category: "Basket",
      image: "https://media.istockphoto.com/id/1408109500/photo/basketball-ball-scoring-the-winning-points-on-basketball-net-hoop-on-basketball-arena.jpg?s=612x612&w=0&k=20&c=hBZwDcu204vZnDaFOBtMWME3OaU46vlqkLiDfKFiFGI=",
      description: "Dive deep into the careers of NBA players with detailed profiles and stats. Explore player achievements, game performances, and career highlights. Stay connected to your favorite NBA stars.",
      Date: "30-11-2024",
    },
    {
      id: 27,
     title: "LIve BasketBall Games",
      category: "Basket",
      image: "https://media.istockphoto.com/id/467634080/photo/basketball-game.jpg?s=612x612&w=0&k=20&c=8BGyRa8U4AXoqstjPXA5t8ukZs6EEUn0PhQsmKOh8Zw=",
      description: "Follow live basketball games with real-time updates, scores, and highlights. Track every slam dunk and buzzer-beater as they happen. Ideal for fans who want to follow the action live.",
      Date: "30-11-2024",
    },
    {
      id: 28,
     title: "Team BasketBall Stats",
      category: "Basket",
      image: "https://media.istockphoto.com/id/1254565557/photo/basketball-player-slam-dunking-ball.jpg?s=612x612&w=0&k=20&c=NpcdqnkKlePu-QcqoCApFTD95MFlX2IazHQ4gbnJAOc=",
      description: "Track team basketball statistics with up-to-date scores, points, and game analysis. Stay informed on team performance and how they stack up against competitors. Perfect for team-focused basketball fans.",
      Date: "30-11-2024",
    },
    {
      id: 29,
     title: "Court BasketBall Data",
      category: "Basket",
      image: "https://media.istockphoto.com/id/1449020875/photo/close-up-of-man-with-basketball-ball-at-sports-field.jpg?s=612x612&w=0&k=20&c=j6WDXEK_ow9ZGtJsLx2giqhMks5dQMlEh8v3rOairkA=",
      description: "Stay informed with detailed basketball court data. Track shots, assists, and defensive stats with precision. Ideal for in-depth basketball analysis and performance tracking.",
      Date: "30-11-2024",
    },
    {
      id: 30,
     title: "Global BasketBall Scores",
      category: "Basket",
      image: "https://media.istockphoto.com/id/1551911414/photo/empty-basketball-court-on-3d-illustration.jpg?s=612x612&w=0&k=20&c=YvuL1dHY2WM-FxXibF5pqt4gED0atDDh0dHcKZc08xA=",
      description: "Follow basketball scores from leagues and tournaments across the world. Stay updated with international basketball competitions, game results, and standings. Perfect for basketball enthusiasts globally.",
      Date: "30-11-2024",
    },
    {
      id: 31,
     title: "NBA Stats Tracker",
      category: "Basket",
      image: "https://media.istockphoto.com/id/1253350295/photo/basketball-players-tackling-for-ball.jpg?s=612x612&w=0&k=20&c=5G_4B96qYdci3FF1yLgulajpk8zAw7y02tuWBcFs9UM=",
      description: "Dive into detailed NBA stats with comprehensive player and team data. Track everything from scoring averages to rebounds and assists. Get all the statistical insights on your favorite NBA players and teams.",
      Date: "30-11-2024",
    },
    {
      id: 32,
     title: "BasketBall Fantasy Leagues",
      category: "Basket",
      image: "https://media.istockphoto.com/id/539208441/photo/basketball-player-makes-slam-dunk.jpg?s=612x612&w=0&k=20&c=lhfwI5Ym-bLy9wb6hh-S7gNjuuC1hcErvSloCWPJNHI=",
      description: "Manage your fantasy basketball team with the latest player stats and rankings. Follow player performances and team data to make informed decisions. Perfect for fantasy basketball league participants.",
      Date: "30-11-2024",
    },
    {
      id: 33,
     title: "BasketBall Players Analysis",
      category: "Basket",
      image: "https://media.istockphoto.com/id/1791303361/photo/high-angle-establishing-wide-shot-of-a-whole-arena-of-spectators-watching-a-basketball.jpg?s=612x612&w=0&k=20&c=HNth5VuPyGddms8HhAnJajlLdTOKDY80odxCg1rSn2k=",
      description: "Analyze basketball player performances with detailed statistics. Get insights into their strengths, weaknesses, and overall impact on the court. Ideal for basketball fans looking for in-depth player reviews.",
      Date: "30-11-2024",
    },
    {
      id: 34,
     title: "National BasketBall News",
      category: "Basket",
      image: "https://media.istockphoto.com/id/1062855462/photo/group-of-multiracial-young-people-playing-basketball-outdoors.jpg?s=612x612&w=0&k=20&c=hnb0YRdHuY2m3iflwrV1kq1d4h5ckMSaRVPt0Gv3Qc8=",
      description: "Stay updated with national basketball news, from local leagues to major tournaments. Get all the breaking news, player updates, and match highlights. Perfect for basketball fans across the nation.",
      Date: "30-11-2024",
    },
    {
      id: 35,
     title: "BasketBall Tournaments",
      category: "Basket",
      image: "https://media.istockphoto.com/id/499331469/photo/female-high-school-basketball-team-playing-game.jpg?s=612x612&w=0&k=20&c=JujSgWGCVK8a30N0qJbn77JW5Z6iLb__0v4iIivPMS8=",
      description: "Keep track of the latest basketball tournaments worldwide. Get tournament schedules, results, and player highlights. Perfect for fans of both domestic and international basketball competitions.",
      Date: "30-11-2024",
    },
    {
      id: 36,
     title: "BasketBall Play offs",
      category: "Basket",
      image: "https://media.istockphoto.com/id/499331257/photo/male-high-school-basketball-team-playing-game.jpg?s=612x612&w=0&k=20&c=_WmcMyhwf0im7YDmH9pFyRauvZUWFOqm5YI3GtSnZPg=",
      description: "Follow the exciting journey of basketball playoffs with up-to-date scores and highlights. Track the performances of teams as they fight for the championship. Ideal for fans who love the intensity of playoff games.",
      Date: "30-11-2024",
    },
  ];
  
  export default all_news;
  